language: go

go:
  # - 1.7.x
  # - 1.8.x
  # - 1.9.x
  # - 1.10.x
  # - 1.11.x
  # - 1.12.x
  # - 1.13.x
  - 1.14.x
  # - tip

addons:
  apt:
    packages:
      - libx11-dev xorg-dev
      - libxtst-dev libpng++-dev
      - xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
      #  - libusb-dev
      - libxkbcommon-dev
      - xsel
      - xclip
      #
      - xvfb
# script:
#  - sudo apt-get update
#  - sudo apt-get install libx11-dev
#  - sudo apt-get install xorg-dev
#  - sudo apt-get install libxtst-dev libpng++-dev
#  # Event:
#  - sudo apt-get install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
#  - sudo apt-get install libxkbcommon-dev
#  # Clipboard:
#  - sudo apt-get install xsel
#  - sudo apt-get install xclip
#  - go test -v .

before_install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v -t -d ./...
  - xvfb-run go test -v ./...
