version: 2

jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: govgo/robotgoci:1.10.3
    working_directory: /gopath/src/github.com/go-vgo/robotgo
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: apt-get update
      - run: apt-get -y install xvfb
      #
      #  override:
      # './...' is a relative pattern which means all subdirectories
      # - run: go get -u github.com/go-vgo/robotgo
      # - run: go get -u golang.org/x/sys/unix
      # - run: go get -u github.com/shirou/gopsutil
      - run: go get -v -t -d ./...
      - run: xvfb-run go test -v ./...
      # codecov.io
      # - run: xvfb-run go test -v -covermode=count -coverprofile=coverage.out
      # - run: bash <(curl -s https://codecov.io/bash)
