version: 2

jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      # - image: govgo/robotgoci:1.10.3
      - image: golang:1.23.0
    working_directory: /gopath/src/github.com/go-vgo/robotgo
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: apt update
      - run:
          apt -y install gcc libc6-dev
          libx11-dev xorg-dev libxtst-dev
          xsel xclip
          # libpng++-dev
          # xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev
      - run: apt -y install xvfb
      #
      #  override:
      - run: go get -v -t -d ./...
      - run: xvfb-run go test -v ./...
      #
      # codecov.io
      # - run: xvfb-run go test -v -covermode=count -coverprofile=coverage.out
      # - run: bash <(curl -s https://codecov.io/bash)
