name: Go
on: [push]
jobs:
  test:
    # name: build
    strategy:
      matrix:
        # go: [1.12.x, 1.13.x]
        os: [macOS-latest, windows-latest] # ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          # if [ -f Gopkg.toml ]; then
          #     curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          #     dep ensure
          # fi

      - name: Build
        run: go build -v .
      - name: Test
        run: go test -v robot_info_test.go
        # run: go test -v .
